### PR TITLE
Require `on_delete` when using foreign keys

### LINKED ISSUE #47: Consider requiring `on_delete` when using foreign keys
You can still do `on_delete: :do_nothing` but this forces you to handle it. It's a little bit of extra effort, but it's valuable to think about ahead of time.

### PR DESCRIPTION
**Pull request by mikeeus**
Closes #47.

### CODE REVIEW

**Comment by paulcsmith** [comment]
Other than that, it looks good 🎉

**Comment by mikeeus** [comment]
Ah yes I forgot about that.

I made the `on_delete` argument not null and it throws a weird error. For example:

```crystal
LuckyMigrator::CreateTableStatement.new(:users).build do
  belongs_to User
end
```
raises: 

```bash
in spec/create_table_statement_spec.cr:133: undefined constant User

    belongs_to User
               ^~~~
```
That's not very helpful. Should I allow nil `on_default` and raise an error instead?

**Comment by paulcsmith** [comment]
Great question. I think you can do something like this:

```
# Add another method definition
macro belongs_to(_type_declaration)
  {% raise “Must use 'on_delete' when creating belongs_to. Example: belongs_to User, on_delete: :cascade %}
end
```

I think that should do the trick

**Comment by mikeeus** [comment]
Okay cool, this is what you were talking about in the [gitter lobby](https://github.com/luckyframework/lucky/blob/master/src/lucky/html_page.cr#L57-L65).

**Comment by paulcsmith** [comment]
Yep! This looks great 👍

**Pull request merged**
