### PR TITLE
Use database url config in create and drop db.

### PR DESCRIPTION
**Pull request by joselfr**
Hello,

I tried to create a docker-compose file to run my lucky webapp and noticed that createdb and dropdb only works on local postgresql.

This pull request changes the behaviour of this two tasks and allow the usage of them with remote postgresql servers.

### CODE REVIEW

**Comment by paulcsmith** [comment]
It looks like I was wrong about this and it has caused some issues for some people in #169. I'm going to try this out on a few projects to make sure it works and then merge it in. Thanks so much @joselfr

**Comment by thegreyfellow** [comment]
Hey guys, I am having trouble connecting my Postgres container with lucky and it seems this pull request fixes it, just asking what's the status on this? Thanks and awesome work on lucky guys 👍

**Comment by paulcsmith** [comment]
This looks good to go. Gonna merge it now. Feel free to use master branch until a new release is out :)

**Comment by paulcsmith** [comment]
Thanks @joselfr!

**Pull request merged**
