### PR TITLE
Add support for jsonb

### PR DESCRIPTION
**Pull request by tzar**
I have added jsonb column generation, mapping to the `JSON::Any` type. I have also added support for it to lucky_record with specs, but I am not sure how to add specs for this to lucky_migrator - advice there would be appreciated!

### CODE REVIEW

**Comment by tzar** [comment]
@mikeeus Thanks for the comprehensive reply! It was easy to follow ☺ I have added support for default values as described and added specs. Re- default types, I went with [JSON::Type](https://crystal-lang.org/api/0.23.1/JSON/Type.html) so you can set strings, arrays etc as well as hashes. Though this seems to have gone missing in crystal v0.25 (`JSON::Any::Type` isn't compatible) so I have re-declared it.

This does mean that you can't pass named tuples, but I don't think you can get named tuples out either as you get `JSON::Any` back from postgres - so in theory default input == output. What do you think?

I have also added some rudimentary quote escaping, I am not very familiar with SQL escaping though so there may be other cases I have missed.

Cheers!

**Comment by mikeeus** [comment]
@tzar No problem, I'm glad it helped! You did a great job, I really like the quote escaping too.
About the NamedTuples, why is it that they wont work? They should get parsed automatically when you call `to_json`.

**Comment by tzar** [comment]
@mikeeus Hmm, I have tried to get this to work but `NamedTuple` needs the keys explicitly defined in the type annotation - e.g `{foo: "bar", bar: 3}` has type annotation of `NamedTuple(foo : String, bar : Int32)`. I could potentially change `default_value` to accept `Object` instead of `JSONDefaultType` and do a `responds_to?(:to_json)`, but then that means that `ColumnDefaultType` will also need to be simply `Object` which I feel is probably too big a change

**Comment by mikeeus** [comment]
You're right, I was mistaken. I don't think using hashes will be a problem then

**Comment by paulcsmith** [comment]
I merged LuckyMigrator into LuckyRecord recently! https://github.com/luckyframework/lucky_record/commit/a74caf9217d0bb9d5b6940c171a2751fcf97899d

If you have time to redo this over there? If not, no worries! I can move this over at some point.

Thanks so much for this BTW. This will be an awesome feature

**Pull request closed without merging**
